name: UbuntuTalks Site Crawler Audits

on:
  workflow_dispatch:

permissions:
  contents: write
  security-events: write

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://ubuntutalks.com/
            https://ubuntutalks.com/about-us
          uploadArtifacts: true

  links:
    runs-on: ubuntu-latest
    steps:
      - name: Check external links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose --no-progress --timeout 30 --max-concurrency 20
            --accept 200,403,429
            --format markdown --output lychee/out.md
            https://ubuntutalks.com/
            https://ubuntutalks.com/about-us
        continue-on-error: true
      - name: Upload Lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md

  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pa11y-ci
        run: npm i -g pa11y-ci
      - name: Run pa11y on homepage
        run: pa11y-ci https://ubuntutalks.com/ --reporter html > pa11y-home.html
        continue-on-error: true
      - name: Upload Pa11y report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-report
          path: pa11y-home.html

  zap_baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://ubuntutalks.com"
        continue-on-error: true
      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: zap-baseline-report.html
