name: UbuntuTalks Site Crawler Audits

on:
  workflow_dispatch: {}         # run manually from Actions tab
  schedule:
    - cron: "0 9 * * 1,4"       # Mon & Thu 09:00 UTC (optional)

jobs:
  lighthouse:
    name: Lighthouse (Perf/SEO/A11y/Best Practices)
    runs-on: ubuntu-latest
    steps:
      - name: Run Lighthouse CI on key pages
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://ubuntutalks.com/
            https://ubuntutalks.com/about-us
          uploadArtifacts: true               # HTML/JSON reports as artifacts
          temporaryPublicStorage: true        # temp LHCI links in logs

  links:
    name: Broken link crawl (Lychee)
    runs-on: ubuntu-latest
    steps:
      - name: Check links on key pages
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose --no-progress --timeout 30 --max-concurrency 20
            --format markdown --output lychee/out.md
            https://ubuntutalks.com/
            https://ubuntutalks.com/about-us
      - name: Upload Lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md

  accessibility:
    name: Accessibility (Pa11y)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pa11y-ci
        run: npm i -g pa11y-ci
      - name: Run pa11y on homepage
        run: pa11y-ci https://ubuntutalks.com/ --reporter html > pa11y-home.html
      - name: Run pa11y on About page
        run: pa11y-ci https://ubuntutalks.com/about-us --reporter html > pa11y-about.html
      - name: Upload Pa11y reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-reports
          path: |
            pa11y-home.html
            pa11y-about.html

  zap_baseline:
    name: Security (OWASP ZAP Baseline)
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline (passive, safe)
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: "https://ubuntutalks.com"
      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: zap-baseline-report.html
