name: UbuntuTalks Site Crawler Audits

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  lighthouse:
    name: Lighthouse (Perf/SEO/A11y/Best Practices)
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Use LHCI CLI directly and write reports to filesystem (no LHCI server).
      - name: Run Lighthouse (homepage)
        run: |
          npx @lhci/cli@0.12.x autorun \
            --collect.url=https://ubuntutalks.com/ \
            --collect.numberOfRuns=1 \
            --upload.target=filesystem \
            --upload.outputDir=./lhci/home
      - name: Run Lighthouse (about)
        run: |
          npx @lhci/cli@0.12.x autorun \
            --collect.url=https://ubuntutalks.com/about-us \
            --collect.numberOfRuns=1 \
            --upload.target=filesystem \
            --upload.outputDir=./lhci/about

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: lhci/**

  links:
    name: Broken link crawl (Lychee)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose --no-progress --timeout 30 --max-concurrency 20
            --accept 200,403,429
            --format markdown --output lychee/out.md
            https://ubuntutalks.com/
            https://ubuntutalks.com/about-us

      - name: Upload lychee report
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md

  accessibility:
    name: Accessibility (pa11y-ci)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pa11y-ci
        run: npm install -g pa11y-ci

      - name: Run pa11y on homepage
        run: pa11y-ci --reporter html --output pa11y-home.html https://ubuntutalks.com/

      - name: Run pa11y on about page
        run: pa11y-ci --reporter html --output pa11y-about.html https://ubuntutalks.com/about-us

      - name: Upload pa11y reports
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-reports
          path: |
            pa11y-home.html
            pa11y-about.html

  zap_baseline:
    name: ZAP baseline scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Run ZAP baseline scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://ubuntutalks.com'

      - name: Upload ZAP baseline report
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: zap-baseline-report.html
